/*
    CORP's Mission Editing Tools
    http://www.corp-arma.fr
*/

#define BOAT_PROJECTION_DIALOG_IDD 423762

#define BOAT_PROJECTION_LIST_IDC 10
#define BOAT_PROJECTION_BOATLIST_IDC 11
#define BOAT_PROJECTION_MAP_IDC 12
#define BOAT_PROJECTION_CLOSE_IDC 13
#define BOAT_PROJECTION_PROJECTION_IDC 14
