/*
    CORP Edition addons
    http://www.corp-arma.fr
*/

#define PARADROP_ADVANCED_DIALOG_IDD 423431

#define PARADROP_ADVANCED_DIVERLIST_IDC 10
#define PARADROP_ADVANCED_DROPLIST_IDC 11
#define PARADROP_ADVANCED_CUSTOM_DROP_PARAMS_CONTROLS_GROUP_IDC 12
#define PARADROP_ADVANCED_ELEVATION_IDC 13
#define PARADROP_ADVANCED_BEARING_IDC 14
#define PARADROP_ADVANCED_MAP_IDC 15
#define PARADROP_ADVANCED_CLOSE_IDC 16
#define PARADROP_ADVANCED_JUMP_IDC 17
